tags:
  - name: submission
    description: submission API

paths:
  /submitReceipt:
    # [POST] submission
    post:
      tags:
        - submission
      summary: Validate Receipt
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/submitReceipt'
      responses:
        200:
          description: 'Submission response'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /validateImages:
    post:
      tags:
        - validation
      summary: Validate Images
      parameters:
        - name: body
          in: body
          description: Image validation data
          required: true
          schema:
            type: object
            properties:
              firstImage:
                type: string
                description: First image (before) base64
              secondImage:
                type: string
                description: Second image (after) base64
              thirdImage:
                type: string
                description: Third image (disposal) base64
              step:
                type: string
                enum: [first, second, third]
                description: Validation step
      responses:
        200:
          description: 'Validation successful'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# definitions
definitions:
  submitReceipt:
    type: object
    required:
      - isValid
    properties:
      isValid:
        type: boolean
        description: Images are valid
      address:
        type: string
        description: User's address
      deviceID:
        type: string
        description: User's device ID

  validateImages:
    type: object
    required:
      - firstImage
      - secondImage
      - thirdImage
    properties:
      firstImage:
        type: string
        description: First image (before) base64
      secondImage:
        type: string
        description: Second image (after) base64
      thirdImage:
        type: string
        description: Third image (disposal) base64
      step:
        type: string
        enum: [first, second, third]
        description: Validation step

schemes:
  - https
  - http
